### ISSUE TITLE
[demo] broken

### ISSUE THREAD

**Issue by ruudk** [rectorphp/getrector.org#270]
See https://getrector.org/demo/792bd08a-4650-4f13-a5ac-b3135a4837ef bottom 

```
Fatal error: Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\proc_open() in /rector/vendor/symfony/console/Terminal.php:162
Stack trace:
#0 /rector/vendor/symfony/console/Terminal.php(148): Symfony\Component\Console\Terminal::readFromProcess('stty -a | grep ...')
#1 /rector/vendor/symfony/console/Terminal.php(114): Symfony\Component\Console\Terminal::getSttyColumns()
#2 /rector/vendor/symfony/console/Terminal.php(97): Symfony\Component\Console\Terminal::initDimensionsUsingStty()
#3 /rector/vendor/symfony/console/Terminal.php(33): Symfony\Component\Console\Terminal::initDimensions()
#4 /rector/vendor/symfony/console/Style/SymfonyStyle.php(51): Symfony\Component\Console\Terminal->getWidth()
#5 /rector/src/Console/Style/SymfonyStyleFactory.php(40): Symfony\Component\Console\Style\SymfonyStyle->__construct(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /rector/bin/rector.php(39): Rector\Core\Console\Style\SymfonyStyleFactory->create()
#7 /rector/bin/rector(4): require_once('/rector/bin/rec...')
#8 {main}
thrown in /rector/vendor/symfony/console/Terminal.php on line 162

```

@JanMikes

**Comment by JanMikes** [comment]
Hi, im on it, might be related to yesterday update of demo to run with php 8

**Comment by JanMikes** [comment]
@ruudk it works now 😉 

https://getrector.org/demo/265c6e32-c321-4fe3-8dd1-859eb1c4f8f2

**Comment by ruudk** [comment]
Thanks for fixing!
